CREATE TABLE IF NOT EXISTS sys_department (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,parent_id BIGINT NULL,name VARCHAR(80) NOT NULL,code VARCHAR(80) NOT NULL,leader VARCHAR(80) NULL,phone VARCHAR(30) NULL,email VARCHAR(120) NULL,sort INT NOT NULL DEFAULT 0,is_enabled TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,created_by BIGINT NULL,updated_at DATETIME NULL,updated_by BIGINT NULL,deleted_at DATETIME NULL,UNIQUE KEY uk_department_code(code),KEY idx_department_parent(parent_id,sort),KEY idx_department_deleted(deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sys_admin_user (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,department_id BIGINT NULL,username VARCHAR(50) NOT NULL,display_name VARCHAR(80) NOT NULL,password_hash VARCHAR(255) NOT NULL,password_salt VARCHAR(255) NOT NULL,email VARCHAR(120) NULL,mobile VARCHAR(30) NULL,is_enabled TINYINT(1) NOT NULL DEFAULT 1,failed_login_count INT NOT NULL DEFAULT 0,locked_until DATETIME NULL,last_login_at DATETIME NULL,last_login_ip VARCHAR(64) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,created_by BIGINT NULL,updated_at DATETIME NULL,updated_by BIGINT NULL,deleted_at DATETIME NULL,UNIQUE KEY uk_admin_username(username),KEY idx_admin_department(department_id),KEY idx_admin_status(is_enabled,deleted_at),CONSTRAINT fk_admin_department FOREIGN KEY(department_id) REFERENCES sys_department(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sys_role (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,code VARCHAR(80) NOT NULL,name VARCHAR(80) NOT NULL,description VARCHAR(255) NULL,is_system TINYINT(1) NOT NULL DEFAULT 0,is_super_admin TINYINT(1) NOT NULL DEFAULT 0,is_enabled TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,created_by BIGINT NULL,updated_at DATETIME NULL,updated_by BIGINT NULL,UNIQUE KEY uk_role_code(code),KEY idx_role_super(is_super_admin,is_enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sys_permission (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,code VARCHAR(120) NOT NULL,name VARCHAR(100) NOT NULL,module VARCHAR(80) NOT NULL,description VARCHAR(255) NULL,is_enabled TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uk_permission_code(code),KEY idx_permission_module(module)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sys_menu (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,parent_id BIGINT NULL,name VARCHAR(80) NOT NULL,menu_type VARCHAR(20) NOT NULL DEFAULT 'page',route_name VARCHAR(100) NULL,route_path VARCHAR(200) NULL,component VARCHAR(200) NULL,icon VARCHAR(80) NULL,permission_code VARCHAR(120) NULL,sort INT NOT NULL DEFAULT 0,is_visible TINYINT(1) NOT NULL DEFAULT 1,is_enabled TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,created_by BIGINT NULL,updated_at DATETIME NULL,updated_by BIGINT NULL,deleted_at DATETIME NULL,KEY idx_menu_parent(parent_id,sort),KEY idx_menu_permission(permission_code),KEY idx_menu_deleted(deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sys_admin_user_role (admin_user_id BIGINT NOT NULL,role_id BIGINT NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(admin_user_id,role_id),CONSTRAINT fk_aur_admin FOREIGN KEY(admin_user_id) REFERENCES sys_admin_user(id) ON DELETE CASCADE,CONSTRAINT fk_aur_role FOREIGN KEY(role_id) REFERENCES sys_role(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sys_role_permission (role_id BIGINT NOT NULL,permission_id BIGINT NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(role_id,permission_id),CONSTRAINT fk_rp_role FOREIGN KEY(role_id) REFERENCES sys_role(id) ON DELETE CASCADE,CONSTRAINT fk_rp_permission FOREIGN KEY(permission_id) REFERENCES sys_permission(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sys_setting (id BIGINT PRIMARY KEY AUTO_INCREMENT,setting_group VARCHAR(80) NOT NULL,setting_key VARCHAR(120) NOT NULL,setting_value TEXT NOT NULL,value_type VARCHAR(20) NOT NULL DEFAULT 'string',description VARCHAR(255) NULL,is_encrypted TINYINT(1) NOT NULL DEFAULT 0,is_public TINYINT(1) NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,created_by BIGINT NULL,updated_at DATETIME NULL,updated_by BIGINT NULL,UNIQUE KEY uk_setting_key(setting_key),KEY idx_setting_group(setting_group)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sys_refresh_token (id BIGINT PRIMARY KEY AUTO_INCREMENT,admin_user_id BIGINT NOT NULL,token_hash CHAR(64) NOT NULL,expires_at DATETIME NOT NULL,revoked_at DATETIME NULL,replaced_by_token_hash CHAR(64) NULL,created_ip VARCHAR(64) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uk_refresh_hash(token_hash),KEY idx_refresh_admin(admin_user_id),KEY idx_refresh_expire(expires_at),CONSTRAINT fk_refresh_admin FOREIGN KEY(admin_user_id) REFERENCES sys_admin_user(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sys_audit_log (id BIGINT PRIMARY KEY AUTO_INCREMENT,admin_user_id BIGINT NULL,module VARCHAR(80) NOT NULL,action VARCHAR(80) NOT NULL,request_path VARCHAR(500) NOT NULL,http_method VARCHAR(10) NOT NULL,request_summary TEXT NULL,status_code INT NOT NULL,ip_address VARCHAR(64) NULL,user_agent VARCHAR(500) NULL,elapsed_milliseconds BIGINT NOT NULL DEFAULT 0,trace_id VARCHAR(100) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_audit_admin_time(admin_user_id,created_at),KEY idx_audit_module_time(module,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sys_file (id BIGINT PRIMARY KEY AUTO_INCREMENT,provider VARCHAR(30) NOT NULL,bucket VARCHAR(100) NULL,object_key VARCHAR(500) NOT NULL,original_name VARCHAR(255) NULL,content_type VARCHAR(100) NULL,size_bytes BIGINT NOT NULL DEFAULT 0,file_hash VARCHAR(128) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,created_by BIGINT NULL,deleted_at DATETIME NULL,UNIQUE KEY uk_file_provider_key(provider,object_key),KEY idx_file_created(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
