<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Lemon.Application\Lemon.Application.csproj" />
    <ProjectReference Include="..\Lemon.Domain\Lemon.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="MySqlConnector" />
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="DbUp.MySql" />
    <PackageReference Include="Quartz.Extensions.Hosting" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Qiniu" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Database\Migrations\*.sql" />
  </ItemGroup>
</Project>
